# ── Paths ─────────────────────────────────────────────────────────────────────
schema_path    := "src/Evaluating_prompt_optimization_techniques_for_water_management_LLM_assistant_with_RAG/tenants/green_roof/sensordata.py"
questions_path := "data/text2sql/deflated_75_sqls_prod.json"
db_path        := "data/water.duckdb"
# ── Endpoints ─────────────────────────────────────────────────────────────────
blablador := "blablador"
kisski    := "kisski"

textgrad_sql_epochs := "3"